defmodule SpecPrompt.CompiledTest do
  @moduledoc """
  Machine-executable form of an AcceptanceTest.

  Generated by `specprompt test-compile` or the `spec_test_compile` MCP tool.
  Compilation is LLM-assisted on first pass, cached by {source_hash, test_index}.
  Human review is required before use in the dark factory pipeline.
  """

  @enforce_keys [:test_index]
  defstruct [
    :test_index,
    :setup,
    :input,
    :assertions,
    :approved,
    :approved_by,
    :compiled_at,
    :compiler_model
  ]

  @type assertion :: map()

  @type t :: %__MODULE__{
          test_index: non_neg_integer(),
          setup: map() | nil,
          input: String.t() | nil,
          assertions: [assertion()] | nil,
          approved: boolean() | nil,
          approved_by: String.t() | nil,
          compiled_at: DateTime.t() | nil,
          compiler_model: String.t() | nil
        }
end
