defmodule SpecPrompt.TestGenerator do
  @moduledoc """
  Generate test scaffolding from acceptance tests.

  Produces code skeletons (ExUnit or generic) from a spec's acceptance tests,
  giving developers a starting point for implementation.
  """

  alias SpecPrompt.Spec

  @type output_format :: :exunit | :generic

  @doc """
  Generate test scaffolding from a parsed spec.

  Returns a string containing the generated test code.
  """
  @spec generate(Spec.t(), keyword()) :: String.t()
  def generate(%Spec{} = spec, opts \\ []) do
    format = Keyword.get(opts, :format, :exunit)

    case format do
      :exunit -> generate_exunit(spec)
      :generic -> generate_generic(spec)
    end
  end

  defp generate_exunit(%Spec{name: name, acceptance_tests: tests, capabilities: caps}) do
    module_name = name |> to_string() |> Macro.camelize()

    test_cases =
      tests
      |> Enum.with_index(1)
      |> Enum.map(fn {test, idx} ->
        test_name = sanitize_test_name(test.given)

        """
          # Acceptance Test #{idx}: #{test.format}
          # Given #{test.given} → #{test.expected}
          test "#{test_name}" do
            # Setup: configure mocked tools for this scenario
            # setup = %{}

            # Act: send input to agent
            # result = Agent.run(input: "#{escape_string(test.given)}")

            # Assert: verify expected behavior
            # assert result =~ "#{escape_string(test.expected)}"
            flunk("Not yet implemented")
          end
        """
      end)
      |> Enum.join("\n")

    cap_comments =
      caps
      |> Enum.map(fn c -> "  #   - #{c.capability}:#{c.scope}" end)
      |> Enum.join("\n")

    """
    defmodule #{module_name}Test do
      use ExUnit.Case

      # Required capabilities:
    #{cap_comments}

      setup do
        # Initialize agent with spec capabilities
        # {:ok, agent: agent}
        :ok
      end

    #{test_cases}end
    """
  end

  defp generate_generic(%Spec{name: name, acceptance_tests: tests}) do
    test_cases =
      tests
      |> Enum.with_index(1)
      |> Enum.map(fn {test, idx} ->
        """
        Test #{idx}: #{test.given}
          Format: #{test.format}
          Given: #{test.given}
          Expected: #{test.expected}
          Status: NOT IMPLEMENTED
        """
      end)
      |> Enum.join("\n")

    """
    # Test Scaffolding for #{name}
    # Generated by SpecPrompt test-gen
    # #{length(tests)} acceptance tests

    #{test_cases}
    """
  end

  defp sanitize_test_name(given) do
    given
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9\s]/, "")
    |> String.replace(~r/\s+/, " ")
    |> String.trim()
    |> String.slice(0, 60)
  end

  defp escape_string(str) do
    String.replace(str, "\"", "\\\"")
  end
end
