defmodule SpecPrompt.MCP.Components.Generate do
  @moduledoc "Generate a SPEC.md scaffold from a natural language description."

  use Anubis.Server.Component, type: :tool

  schema do
    field(:description, :string,
      required: true,
      description: "Natural language description of the agent"
    )

    field(:name, :string,
      required: true,
      description: "Agent name (lowercase-hyphenated)"
    )

    field(:author, :string, description: "Author name or team")
  end

  @impl true
  def execute(params, frame) do
    desc = get_param(params, :description)
    name = get_param(params, :name)
    author = get_param(params, :author) || "unknown"
    today = Date.utc_today() |> Date.to_iso8601()

    scaffold = """
    ---
    name: #{name}
    version: 0.1.0
    runtime: any
    author: #{author}
    created: #{today}
    updated: #{today}
    tags: []
    dependencies: []
    ---

    ## Purpose

    #{desc}

    ## Capabilities

    - example:read (TODO: define capabilities)

    ## Constraints

    - TODO: define behavioral constraints

    ## Acceptance Tests

    - Given TODO → expected behavior

    ## Architecture

    TODO: describe system architecture.

    ## Dependencies

    - TODO (type, location)

    ## Changelog

    - 0.1.0 (#{today}): Initial scaffold generated by SpecPrompt
    """

    {:reply,
     Anubis.Server.Response.tool()
     |> Anubis.Server.Response.text(String.trim(scaffold)), frame}
  end

  defp get_param(params, key) when is_map(params) and is_atom(key) do
    Map.get(params, key, Map.get(params, Atom.to_string(key)))
  end
end
